### ISSUE TITLE
Compatibility with Drone CI

### ISSUE THREAD

**Issue by MattSurabian** [thockin/go-build-template#10]
Thanks for this repo, I've been really loving how easy it makes getting projects up off the ground! I'm curious about how this would work in a container based CI environment like Drone.

In Jenkins or Travis, using Make directly seems like a clear course of action. But what about when using something like Drone where the assumption is that your build is going to take place in an ephemeral Docker container already?

I'd like to leave Make in place for local folks that aren't hooked into Drone but I'm not sure the best way to make the two workflows play nice next to each other. My current thought is to try to offload drone's build step directly to the shell scripts in `./build` and filling in the environment variables where needed, but maybe I'm missing a better option? Maybe it's just the case that using a skeleton like this remove the utility of a service like Drone or on the flipside, using something like Drone means having to go all in, including locally.

Curious to hear folks' thoughts.

**Comment by thockin** [comment]
Perhaps you want a `make native` rule that runs the build natively, so the on-my-desktop experience is `make` but drone does `make native`.  I think that might be OK.  PRs welcome.

**Comment by MattSurabian** [comment]
Thanks for replying. That's what I ended up doing and it worked fine. Ultimately we moved off of Drone for various reasons.
