### ISSUE TITLE
Work flow - go get

### ISSUE THREAD

**Issue by pjfoley** [thockin/go-build-template#11]
I was wondering how you manage dependant packages when compiling within the docker container?

**Comment by timoreimann** [comment]
@pjfoley vendoring up-front (outside the Makefile) in one solution. it also guarantees reproducible builds.

**Comment by alexmario74** [comment]
Sorry, could you explain a bit more? I'm looking to organize my project and go-build-template is a good starting point, great work anyway.

Just could not understand which policy to follow as I'm going to need external pages like seelog and mongodb drivers. 

I was looking to govendor, but not sure how to use it from this scaffolding.

It's not just the golang project, I'm worried about the docker image, as I don't want to have the external dependencies that generate an image every time, even they are not changed.

Do you have any hint?

**Comment by air33** [comment]
You can use [godep](https://github.com/tools/godep),
From [tamalm](https://www.reddit.com/user/tamalm)

1. install godep. $ go get github.com/tools/godep
2. create 'vendor' folder in your project root dir.
3. run $ godep save (this will do the magic). Check vendor folder. You'd see all dependencies.


please read [here](https://www.reddit.com/r/golang/comments/4c0up7/how_to_use_go_vendoring/?st=j69ja47t&sh=65af3a79)

**Comment by alexmario74** [comment]
Thanks, I'll check this.

In the while I started with glide.

It looks fine for now.
