### ISSUE TITLE
`ERROR: invalid tag "...": repository name must be lowercase` in "Create and publish image" workflow when forked with uppercase in owner or repo name

### ISSUE THREAD

**Issue by jingyuanliang** [thockin/go-build-template#125]
https://github.com/thockin/go-build-template/blob/8d156007dac76fe07f663a08c0ae3658630d4983/.github/workflows/publish.yaml#L21

**Comment by thockin** [comment]
Is there a 'tolower()' sort of function in jinja?  I don't know.

Option 1: change it to hardcode the name you want
