### ISSUE TITLE
Consider: figure out generated files (at least protoc)

### ISSUE THREAD

**Issue by jbeda** [thockin/go-build-template#2]
It will be more and more common to have generated files and things like protoc.  Protoc itself is super complicated to get working correctly and really lends itself to containerized building.

Other generated files (`go generate`) aren't quite so complicated and it should be easy to explicitly run those.

**Comment by thockin** [comment]
PRs welcome.  I know this is almost a year old.  Sorry.  I didn't "watch" my own repo...

**Comment by damianoneill** [comment]
@thockin, I'm interested in doing this PR, specifically the protoc component.  Can you describe how you'd like this implemented.   

Thanks,
Damian.

**Comment by damianoneill** [comment]
Looking at [proto gen](https://developers.google.com/protocol-buffers/docs/reference/go-generated#invocation) the implication is that the proto files will exist in the src directory (assume pkg or cmd) and the generated files will be written to build/gen.  

Does this seem like a reasonable approach?

**Comment by gadieichhorn** [comment]
looks an old ticket... is this still valid or implemented?

Do you have support for volume mounting? for some cases, this will be fine, like config, but for web templates, for example, would like it to be part of the image.

adding my vote on this ticket, 

managing template files or any resources needed especially now were you have a multi-image build support.
1. how to add any resources to the image? or is there a volume support
2. how to add resources to the right image under cmd?

proposal:
create a resources folder with a matching application name folder for each docker image.
add these resources to the matching container image.

resources
 -- app-1
   -- index.html
   -- 
 -- app-2
   -- msg.proto

**Comment by thockin** [comment]
I'm open to PRs along this line, sure.
