### ISSUE TITLE
Dependency management seems broken?

### ISSUE THREAD

**Issue by delapsley** [thockin/go-build-template#21]
Hi Tim:

Thanks for putting together this excellent template. I'm having issues with dependency management and would appreciate any pointers.

The build image does not appear to have git installed, and doesn't seem to be correctly fetching dependencies. I could not figure out how this is done from reading through the Makefile. I would greatly appreciate any pointers you can provide.

Thanks!

**Comment by thockin** [comment]
I assume dependencies are checked-in under vendor/.  Anything else depends on the kindness of strangers to keep my build working.  I have experience upstream repos which force-push and obliterate the hash I depend on.  The only safe solution is to check-in my deps.
