### ISSUE TITLE
make build binary name

### ISSUE THREAD

**Issue by damianoneill** [thockin/go-build-template#23]
I changed the variable BIN to 

```
# The binary to build (just the basename).
BIN := planner
```

When doing a build 

```
$ make build
building: bin/amd64/planner
```

Results in binary named myapp, should this not be a binary called planner (in my case)?

```
$ tree bin
bin
└── amd64
    ├── darwin_amd64
    └── myapp

2 directories, 1 file
```

**Comment by thockin** [comment]
If I recall, The extra directory is a result of the way Go does
cross-compiles.  Compilation for the native platform uses one style of path
and a different style for cross-compiles.  The template just bind mounts
both to the same place, so the binary is always `bin/$ARCH/$BIN`, and the
extra directory is just left laying around.

We could try to get more clever, but there wasn't an obvious answer.

**Comment by damianoneill** [comment]
Sorry Tim that isn't the issue, it's the bin name.  In my example should it not be 'planner'?  It's currently generating 'myapp' even though I changed the BIN env variable.  

Regards,
Damian ONeill

**Comment by thockin** [comment]
oh!  Sorry.

```
$ git grep myapp
Makefile:BIN := myapp
```

If you change BIN it should work.  Can you run that `git grep` ?  Can you `make clean` and then build?

**Comment by damianoneill** [comment]
Np, see below. 

doneill at doneill-mbp in /projects/github/planner on master [!]
$ git grep myapp

doneill at doneill-mbp in /projects/github/planner on master [!]
$ git grep planner
Makefile:BIN := planner

doneill at doneill-mbp in /projects/github/planner on master [!]
$ make clean build
rm -rf .container-* .dockerfile-* .push-*
rm -rf .go bin
building: bin/amd64/planner

doneill at doneill-mbp in /projects/github/planner on master [!]
$ tree bin
bin
└── amd64
    ├── darwin_amd64
    └── myapp

2 directories, 1 file

**Comment by thockin** [comment]
Ahh, you need to rename `cmd/myapp` to `cmd/planner` because we `go install ./...`.  Not sure how to solve that - we want to install it all for fast rebuild, but go assumes teh dirname == binary name.  Will update README.

**Comment by damianoneill** [comment]
Confirmed, thanks Tim.

**Comment by thockin** [comment]
Fixed.
