### ISSUE TITLE
Pulling Images Across Boundaries

### ISSUE THREAD

**Issue by chrisccoy** [thockin/go-build-template#32]
I am grateful for this repo, as it has accelerated my understanding. I do have a question regarding versioning. How does the "git" tagging actually work in the real world, in terms of image pulling etc, when you are trying to grind through a container to container test? (each container-image has a different revision, which you are simultaneously improving). Are you just using a local docker repo and referencing latest? 
 
I am definitely missing something in the workflow on how to annotate my k8s yaml to accept a particular branch versus a hard coded version.

**Comment by thockin** [comment]
I'm not sure I understand the question.  This uses git's own notion of tags to produce a container with the same tag.  There's not a formal relationship except that they have the same string value.  Every git commit you make will produce a different tag value (e.g. `v1.12.0-alpha.0-530-g6b74955ea4`) and if you make a real tag (`git tag`) it will use that.

You can push those image somewhere if you test in a remote site or you can just use them locally to pass tests.

**Comment by chrisccoy** [comment]
OK, thank you. I think that's what I was missing. `git tag`
