### ISSUE TITLE
multiple BINs

### ISSUE THREAD

**Issue by lemonlinger** [thockin/go-build-template#33]
If there were multiple BINs under cmd/, how should I make ?

**Comment by thockin** [comment]
I haven't thought about it - I am open to ideas

**Comment by alok87** [comment]
I been doing this by making every binary a variable in Makefile
```
BIN := nodeagent
BIN_NODEAGENT := nodeagent
BIN_DNSCONTROLLER := dnscontroller
BIN_LBCONTROLLER := lbcontroller
BIN_FASTSCHEDUER := fastscheduler```
`make BIN=nodeagent all`
Right way to version all of them, still to figure out.

**Comment by westwin** [comment]
i'm thinking the same

**Comment by austinhrdt** [comment]
I've been able to do this with
```
BINS := app1 app2 appN
```
but needed to modify a lot of the Makefile. Also in my case I'm on windows and develop within ubuntu container so sadly I couldn't find a way to keep the containerized build environment due to complications with the bind mounts. I did this a while ago but if you're curious I just threw it in a repo  [here](https://github.com/austinhrdt/go-build-template).

**Comment by gadieichhorn** [comment]
I am also interested in how to make this build multiple binaries in a single repo. 
Don't want to duplicate the makefile for each service.

Can anyone share the makefile that can do this? 

I like the:
```
BINS := a b c d 
```
approach  (@austinhrdt ) but still maintain the docker build container (@alok87 )
thanks.

**Comment by thockin** [comment]
When building a container - do you expect all of the bins in one image or multiple images?

**Comment by westwin** [comment]
I'd prefer multiple images

> When building a container - do you expect all of the bins in one image or multiple images?

**Comment by austinhrdt** [comment]
Multiple images otherwise service becomes a monolith, although this begs the question if its even good practice to produce multiple services from a single repository...

**Comment by thockin** [comment]
I take no position on how people should use this repo.  Multiple binaries
is common enough, but the question is open - one container artifact holding
multiple binaries is sometimes useful, and sometimes you want N containers
each on binry.  I just don't want to do BOTH :)

**Comment by thockin** [comment]
I just added support for multiple binaries.  It does not have support to build just one, though.
