### ISSUE TITLE
Distribute binaries with a one liner script

### ISSUE THREAD

**Issue by alok87** [thockin/go-build-template#35]
Script to install the binary with a one liner bash command.

### Goals
- Script should work in all platforms - macOS, linux..
- Script should work both in private Github repos and public repos.

I was writing a golang project and i had to distribute binaries - so have written some scripts to do it. It is a very common use case and it would be nice to have it here. :)

Something like (below works in non private repos - to make them work in private repos you need to use github assets api)
- https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-with-curl-on-linux
- https://github.com/vapor-ware/ksync/#linuxmacosx

**Comment by thockin** [comment]
I appreciate the enthusiasm, but I wan to keep this repo as a starting point for projects, rather than a do-it-all framework.  It's already somewhat stale with Docker multi-stage builds and some of the Go tooling changes.

Thanks, really.
