### ISSUE TITLE
fail to build on older depnednecy version

### ISSUE THREAD

**Issue by gadieichhorn** [thockin/go-build-template#43]
Great tool and thanks for sharing it.

I am trying to use go zeromq binding but finding errors with make file build I think because the version is pre go mod or doesn't have support for vendor mod.

```
require (
	github.com/zeromq/goczmq v4.1.0+incompatible
)
```

> make 

```
making bin/linux_amd64/dwx
build github.com/zeromq/goczmq: cannot load github.com/zeromq/goczmq: no Go source files
make: *** [Makefile:96: .go/bin/linux_amd64/dwx.stamp] Error 1
```
Any idea how to fix this?
Thanks.

**Comment by thockin** [comment]
I don't know off the top of my head, but I only know how modules REALLY work superficially.  Did you figure this out?
