### ISSUE TITLE
ARMv7 support

### ISSUE THREAD

**Issue by gadieichhorn** [thockin/go-build-template#46]
Thanks for this awesome build template

How can I make an image fit for Raspberry PI 3 B -> ARMv7?

The image has:

> docker image info

```    
"Architecture": "amd64",
```

>  docker service create ...

fail for  

```
1/4: no suitable node (unsupported platform on 4 nodes) 
2/4: no suitable node (unsupported platform on 4 nodes) 
3/4: no suitable node (unsupported platform on 4 nodes) 
4/4: no suitable node (unsupported platform on 4 nodes) 
```

can I add anything to the build to make this work?

using docker run works (and container run fine) on same image but swarm seemed to do more checks.

What did I get wrong or how to fix this?
Thanks in advance

**Comment by gadieichhorn** [comment]
additional info...

it is possible to build docker images directly on the ARM device that works with docker-machine.
Maybe all I need is to run the make on a remote docker host. When I try that I am missing the build scripts.

is there a way to change the make file to allow that to run?
Anyone done this successfully?

```
 not found
make: *** [Makefile:120: go-build] Error 127
```

also might be needed is to tell the script what container ARCH we want, in this case ARM.

**Comment by thockin** [comment]
Can you say more about what you are doing?  This already supports building for multiple architectures, including linux/arm (which should be correct for RasPi).

Running `make GOOS=linux GOARCH=arm` should give you binaries in bin/linux_arm.  `make container GOOS=linux GOARCH=arm` should build container images.

What is not working?

**Comment by gadieichhorn** [comment]
Thanks for responding

I run (linux/fedora)

> make all-container 

then 

> docker push ... 

then on the RPI (ARMv7 / RPI B/3 )

> docker pull ...

> docker  service create ...

**Comment by thockin** [comment]
Did you `docker all the images`?  Are you pulling the right architecture tags?

Try `make manifest-list` instead :)

**Comment by gadieichhorn** [comment]
After doing more tests I can confirm the only issue is with stack deploy that for some reason doesn't like to deploy this go service on RPI as stated above.
directly creating service and scaling works fine on swarm or running the arm container directly.

I think this is to do with my stack deploy script and not related to the image. for now I can close this ticket.
