### ISSUE TITLE
PUBLISH tags feature: Option to release all sem version formats

### ISSUE THREAD

**Issue by alok87** [thockin/go-build-template#50]
We have added a publish tag feature like this here https://github.com/practo/k8s-worker-pod-autoscaler/blob/master/Makefile#L14-L17

This helps in releasing all the sem versions together.

```
$ make push
pushed: practodev/workerpodautoscaler:v1.0.0-19-g59d0d48
pushed: practodev/workerpodautoscaler:v1.0
pushed: practodev/workerpodautoscaler:v1
```

Exact version are the best but a lot of people use it like this also.

**Comment by thockin** [comment]
I like the idea, but I would make it a whole different "strategy" block.  PR welcome!
