### ISSUE TITLE
Add lint support 

### ISSUE THREAD

**Issue by jingyuanliang** [thockin/go-build-template#64]
We have a project based on this go-build-template and @bcheung added linter (golangci-lint) support in it: https://github.com/GoogleCloudPlatform/netd/commit/046dac12ad20c304d0bcef6f82bb8f0969228b8a. However this makes updating from the template a bit annoying. I wonder if it should be considered to include a linter in the template, either by absorbing this one or implementing a new one.

**Comment by thockin** [comment]
Good idea.  I just added `golangci-lint` but no config file, so you can drop your own config in.

I dislike the format part - I thing `gofmt` is the sane default (that's how most editors are configured).  If ther are things I can do to make it easier to integrate, please suggest.
