### ISSUE TITLE
Using multiarch manifest as BASEIMAGE doesn't just work

### ISSUE THREAD

**Issue by jingyuanliang** [thockin/go-build-template#70]
It's attractive to put multiarch manifest path in the BASEIMAGE variable, especially when some images (eg. distroless-iptables) don't have arch-suffixed versions. However this use doesn't just work, since `docker build` runs on the native arch and always fetch the native base image and build for all platforms on top of it.

**Comment by thockin** [comment]
Sorry, I am not clear on what you are saying.  what exactly is not working?

**Comment by jingyuanliang** [comment]
I made the change https://github.com/kubernetes-sigs/ip-masq-agent/commit/a8acaa4ec623ee34df52ffb6baffd76d98c6e310 and thought it should just work, but it ended up building ARM64 images using AMD64 base image. The change to use multiarch manifest must happen, because we're switching to distroless-iptables https://github.com/kubernetes-sigs/ip-masq-agent/commit/cf9563a9605c65fc9d67dc8391d61bad89fc3295 soon later, which doesn't have suffixed versions (eg. distroless-iptables-amd64).

I ended up using `buildx` https://github.com/kubernetes-sigs/ip-masq-agent/commit/fadebd32edf3b017e420c793c5bd8d2f5f54bb33 and I could send this as a PR here, but it's extra work if the base image is not multiarch, so I wonder if you have a better / smarter solution to accommodate the use of multiarch manifest as BASEIMAGE.

**Comment by thockin** [comment]
I see.  I'd be happy to look at a PR to make it more concrete.

**Comment by jingyuanliang** [comment]
Do you think it's better to use buildx (in all cases or when necessary) or try to parse the manifest ourself?

**Comment by thockin** [comment]
I see now what you mean.  I converted it to use buildx, which reveals that this would never have worked for Windows because windows requires a special base-image (YUUUUUUCK).

**Comment by thockin** [comment]
I pushed my work - tell me if that doesn't do what you were thinking?

**Comment by jingyuanliang** [comment]
I haven't tested it but based on my experience, simply using buildx doesn't always work in Louhi and the buildx-setup part (similar to https://github.com/GoogleCloudPlatform/netd/commit/1d27509140cd246dcf05756a8fb5c30d47a35038) is critical. Otherwise, it uses the correct base image from the manifest, but doesn't run the RUN commands in Dockerfile in the correct arch (so got an "exec /bin/sh: exec format error").

You can decide if you want to include this buildx-setup stuff in the template, or leave it to whoever adds RUN commands.

**Comment by thockin** [comment]
This template depends on docker and now buildx.  I used buildx in git-sync
and it works well, but I don't use louhi there.  How else is one to
cross-build docker images?

**Comment by jingyuanliang** [comment]
This issue is not really specific to Louhi, but we have some projects based on this template and built by Louhi. The issue with Louhi is that it starts with a clean environment without buildx prepared so we need to inject the preparation into the build workflow. See https://cloud.google.com/kubernetes-engine/docs/how-to/build-multi-arch-for-arm#prepare-build-env-with-x86-vm-only

**Comment by thockin** [comment]
Funny, I initially had this logic in the Makefile but it felt hostile to
always run it (sadly, buildx is pretty machine-global, as I know how to use
it).  I will see if I can make that cleaner.

**Comment by thockin** [comment]
How about now?

**Comment by jingyuanliang** [comment]
Looks like it should work, but I don't have a good way to test it on Louhi and I don't want to just update an existing image to use it to prevent accidental breakage. Maybe I can try it the next time when I need to build a new image or refresh an existing one.

**Comment by jingyuanliang** [comment]
Reporting back on this - it looks working correctly, except for that it doesn't work with `make -j <value>`. I'll open another issue for this.
