### ISSUE TITLE
Duplicated runs in tests workflow

### ISSUE THREAD

**Issue by jingyuanliang** [thockin/go-build-template#76]
https://github.com/thockin/go-build-template/blob/master/.github/workflows/tests.yaml uses matrix `go-version: [ "1.17", "1.18", "1.19" ]` but this is not passed into the `make` command, so all runs of the tests workflow are actually the same.

**Comment by thockin** [comment]
Good catch!

**Comment by thockin** [comment]
Fixed at HEAD
