### ISSUE TITLE
Makefile does not accommodate working directory with spaces

### ISSUE THREAD

**Issue by seh** [thockin/go-build-template#8]
If the current working directory (as presented by _pwd_) contains spaces, the [Docker volume mounting arguments](https://github.com/thockin/go-build-template/blob/master/Makefile#L86) fail to parse correctly. Either quote these arguments appropriately, or document that the project can't work in a directory whose name contains spaces.

I'll submit a proposed fix shortly.

**Comment by thockin** [comment]
Fixed
